version: "3.11"
services:
  questions:
    build: ./service_questions/
    restart: always
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - bewisenet
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    restart: always
    networks:
      - bewisenet
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  bewisenet:
    driver: bridge
